apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jforg-ingress
  namespace: artifactory-oss
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx
  rules:
    - host: jforg.artifactory.devops.myapp.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: artifactory-oss
                port:
                  number: 8082